### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guides-template#34]
- [x] review and update wiki in https://github.com/OpenLiberty/draft-guides-template/wiki
- [x] review and update the issue templates 
  - https://github.com/OpenLiberty/draft-guides-template/issues/12
  - https://github.com/OpenLiberty/draft-guides-template/issues/15
- [x] prepare/review all required docs in team repo
- [x] fix #30

**Comment by DannyS03** [comment]
Nimrah created:
- https://github.ibm.com/was-liberty/openliberty-guides-team/blob/master/intern-content/intern-transition/wekan-board.md
- https://github.ibm.com/was-liberty/openliberty-guides-team/blob/master/intern-content/intern-transition/qa-draft-site.md
- https://github.ibm.com/was-liberty/openliberty-guides-team/blob/master/intern-content/intern-transition/lgdev-site.md

**Comment by NimG98** [comment]
- [ ] I think `:page-tags: ['MicroProfile', 'Maven', 'Java EE', 'Gradle']` should be removed from https://github.com/OpenLiberty/draft-guides-template/wiki/README-breakdown.
The new way is adding the guide to the tags listed in the [guide_tags.json](https://github.com/OpenLiberty/guides-common/blob/master/guide_tags.json)

- [ ] And should also mention that when publishing a guide, the guide needs to put under a certain category in the [guide_categories.json](https://github.com/OpenLiberty/guides-common/blob/master/guide_categories.json)

**Comment by DannyS03** [comment]
**openliberty-guides-team on IBM GitHub**

We should delete the following wikis:
- current focus
- daily scrum meeting minutes 
- guides category page description 
- guides for MicroProfile Tutorial
- testing dev build for 1900x

**Comment by DannyS03** [comment]
In regards to https://github.com/OpenLiberty/draft-guides-template/issues/30: 
  - I believe most of the guides are already using `hide_tags= …`
  - hotspot line numbers already updated in [Guidelines for Structure and Styles](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles) in **draft-guides-template**. 
- OS specific tab example added to [Guidelines for Structure and Styles](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles).

---

- page-tags attribute updated in [README breakdown](https://github.com/OpenLiberty/draft-guides-template/wiki/README-breakdown).

**Comment by DannyS03** [comment]
- Dockerfile best practices & environment cleanup: https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Dockerfile
