### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guides-template#4]
In general, looks good.

Some minor comments:

- "Git triangular workflow" <- I know git but I'm not sure what that term refers to. Can we have a link to where one would go to learn about it? (eg in the GitHub help? or some useful tutorial online somewhere)
- Would be useful to provide links to the Asciidoc help (rather than just the project page): https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/ and https://asciidoctor.org/docs/asciidoc-writers-guide/
- "explains" <- should that be "explain"?
- nested numbering in step 2 has gone a bit weird (in the GitHub markdown preview anyway).
- copyright year in the sample says 2017 - needs updating.
- the example guide lists 'MicroProfile guide' but points to the CDI intro guide. The guides (REST and CDI) should be referred to by their published titles.

In the self-review checklist:

- what is 'best coding practices' and 'correct structure'? can we point them to something explaining that?
- is `role="no copy"` still necessary? I think with the new guide template it isn't but I'm not sure where we're at with that.
- does "ex)" mean 'for example'? If so, it should be just the more usual "e.g." or just "for example". Would be useful to put those page attribute names in monospace too for clarity.

**Comment by cbridgha** [comment]
Triangle workflow:  https://blog.github.com/2015-07-29-git-2-5-including-multiple-worktrees-and-triangular-workflows/#improved-support-for-triangular-workflows

**Comment by JunyiSun** [comment]
Thank you for the link! @cbridgha

**Comment by JunyiSun** [comment]
Issues are fixed. Thank you!
