### ISSUE TITLE
Instruction Feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guides-template#5]
- [x] Install and know the basics of Maven. => May be good to include Gradle, as we will have all guides to run with gradle in the future? 

- [x] Step 3: I think it looks better to have the paragraphs at the same indentation as the bullets, so they don't look like they're separate information. 

- [ ] Write a guide that follows the README.adoc template (APPENDIX A) in the guides-template repository. => I think this says, the README.adoc is shown in the APPENDIX A, and it's available in the guides-template repository. Hm, looks like the template adoc is combined with the getting started instruction.. we need to discuss about this. 
**Yes, I think YK approved it last time when we discussed about it.**

- [x] Introduce and explain the parts of code that you removed during Step B and tell the users where to copy and paste the code. => what is Step B?

- [x] Describe the topic you wrote, add a link to the repository that contains the complete draft of your guide, and contact the Open Liberty team. => not sure about "contact the Open Liberty team" as there's no specific contact info attached. Perhaps "the Open Liberty team will be notified"? 

- [ ] Instructions for how to sign and submit these agreements are provided in each document. => in each of the documents.
**JS: I asked Sarah, she said it's okay and more concise to say `in each document` in this sentence.**

- [x] After the Open Liberty team approves your guide, request to create a draft guide repository. Name your new repository draft-guide-{name} in the public Open Liberty GitHub repository. 
=> Not sure everyone, including external contributors can or knows how to request creating a draft guide repo.. or this should say, the OL team will request to create a draft guide repo and state it on the issue. 
=> May be good to have the repo name example as `draft-guide-{projectid}` to watch the projectid used in the README.adoc. Because otherwise, there's more trouble with the git clone command. 
=> "the public Open Liberty GitHub repository" should be "the public Open Liberty Project GitHub organization". Perhaps do not need the word "public". 

- [x] You can see your feedback from the Issues section in your draft-guide-{name} repository in a few days.
=> keep repository name consistent, if changed based on above comment
=> not sure about "in a few days..", perhaps "as soon as possible"? 

- [x] APPENDIX A: A template README.adoc
INSTRUCTION: Please remove all the instructions before APPENDIX A prior to commit. => The "INSTRUCTION" cap'ed word looks like this is the instruction to follow, but it's actually telling user to delete all the instructions in the template readme.adoc. IMO, don't need "INSTRUCTION:". 

- [x] Note that the include statements in the template readme.adoc doesn't get rendered properly, ie, this line is displayed, "Unresolved directive in <stdin> - include::{common-includes}/gitclone.adoc[]". May need to clarify if user just copies the content from the appendix. 

- [x] Have all lines in template readme.adoc fit in one page to eliminate left-right scrolling. Currently looks like the "========================" dividers are the ones not fitted. 

- [x] EXAMPLE: The following block demostrates how different sections look like for a to do application. => is "to do" spelled one word or two? There are both in the template readme.adoc.

- [x] Need to verify if these are still accurate: 
// Use the following include to pull in the Liberty start/stop server instructions from the
// guides-common repo.
Unresolved directive in <stdin> - include::{common-includes}/mvncompile.adoc[]
// Instructions to rebuild the application

**Comment by JunyiSun** [comment]
@evelinec Fixed.

**Comment by evelinec** [comment]
Thanks @JunyiSun, looks good. Just one thing: 

- [ ] Step 6, "Open Liberty GitHub" sounds a bit funny. I think you want to refer to the Open Liberty Project on GitHub.com, ie, https://github.com/OpenLiberty.
