### ISSUE TITLE
Review feedback from Gilbert

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guides-template#9]
-  Should the source files contain the copyright section at the top?
-  Add a check point to the Technical review section of the Self Review Checklist wiki
    - Make sure all source files contain the copyright section at the top and the right license year
- [x] Guidelines-for-Structure-and-Styles wiki, 
  - [x] should mention that if include text in README.adoc file, 
    - use tags
      - include::finish/pom.xml[tags=bootstrapProperties]
    - instead of lines 
      - include::finish/pom.xml[lines=111..115]
  - [x] In the Example of Writing tests section, the assertEquals statement misses a semi-colon at the end

**Comment by yeekangc** [comment]
We should double check on the copyright statements for source files especially if they originated from non-IBM contributors.

**Comment by JunyiSun** [comment]
@gkwan-ibm I think we have this point in the wiki
"
should mention that if include text in README.adoc file,
use tags
include::finish/pom.xml[tags=bootstrapProperties]
instead of lines
include::finish/pom.xml[lines=111..115]
"

**Comment by JunyiSun** [comment]
Since we don't put the copyright there anymore, we can close it
